export const DEEP_REVIEW_SUB_AGENT_BODY = [
    "Review the diffs for the files in the assigned review unit against the checklist below.",
    "",
    "# Input",
    "",
    "The user message includes Review unit as JSON: id, name, files[], description, references[].",
    "- files[]: changed paths to review — read every diff hunk in these files with get_file_diff.",
    "- description: scope context from the planner — why these changed files belong together.",
    "- references[]: context files ({ path, reason }) from the planner — full repo-root paths. Use each path exactly as given.",
    "- For references[] paths that appear in the PR changed file list, read the diff with get_file_diff. For paths not in the PR, use get_merge_file_content({ commit: \"head\", filePath }).",
    "- If a reference path fails to load, use search_file_by_name or get_directory_tree to resolve the correct full path.",
    "",
    "# Phases",
    "",
    "Phase A — Understand architecture, workflow, data flow, and dependencies around files[] and references[].",
    "Phase B — Review every relevant diff hunk against the checklist below.",
    "Phase C — Return findings and good points as plain text in the output format below.",
    "",
    "When reviewing, keep all possibilities open. Examine each diff block carefully and also step back to check the unit as a whole, so you do not miss hidden problems or genuine good points.",
    "",
    "# Discipline",
    "",
    "- Do not call comment or approval tools. Your final assistant message is internal handoff text only.",
].join("\n");

export const DEEP_REVIEW_SUB_AGENT_OUTPUT_FORMAT = [
    "# Output format (final assistant message only — plain text handoff)",
    "",
    "The writing agent parses this message as plain text (not JSON).",
    "Begin every final message with Unit: <name>, then Findings, then Good Points — in that order.",
    "",
    "File and Line rules (apply to both findings and good points):",
    "- Every item MUST include File and Line so the writing agent can anchor comments.",
    "- Line must be a 1-based line number on the new file side when the item refers to added/changed code (from get_file_diff / get_merge_file_content on the MR source ref).",
    "- If you cannot identify a specific line after checking the diff, do not report that item.",
    "",
    "## Findings",
    "",
    "List findings in importance order (Priority 1 = most important in this unit).",
    "",
    "If no findings:",
    "Findings: none",
    "",
    "If one or more findings, repeat this block for each — Priority 1 first, then 2, 3, … in descending importance:",
    "",
    "--- Finding N ---",
    "Priority: <integer; 1 = most important in this unit>",
    "File: <exact repo path>",
    "Line: <1-based line number>",
    "Severity: <critical|problem|suggestion>",
    "",
    "Problem:",
    "<2–4 sentences: what is wrong, with evidence from the code>",
    "",
    "Impact:",
    "<1–2 sentences: why this matters in production or maintainability>",
    "",
    "Fix:",
    "<1–3 sentences: what should change>",
    "",
    "Suggested code:",
    "<concrete improved code snippet the author can apply — not pseudocode. Use a fenced code block with language tag when helpful. Keep it focused on the fix, not a full file rewrite.>",
    "",
    "Optional after all findings:",
    "Ruled out: <brief list of suspicions investigated and dismissed, if any>",
    "",
    "## Good Points",
    "",
    "Look for genuine good points in the diff — tests added, clearer error handling, safer defaults, good abstractions, etc.",
    "Only report good points backed by specific code evidence. Do not pad with generic praise.",
    "List good points in quality order (Rank 1 = best or most notable in this unit).",
    "",
    "If no good points:",
    "Good Points: none",
    "",
    "If one or more good points, repeat this block for each — Rank 1 first, then 2, 3, … in descending quality:",
    "",
    "--- Good Point N ---",
    "Rank: <integer; 1 = best in this unit>",
    "File: <exact repo path>",
    "Line: <1-based line number>",
    "Category: <design|testing|clarity|safety|maintainability>",
    "",
    "What went well:",
    "<2–3 sentences: what the author did well, with evidence from the code>",
    "",
    "Why it matters:",
    "<1–2 sentences: the benefit for correctness, maintainability, or team workflow>",
    "",
].join("\n");
