export const DEEP_REVIEW_COMMENT_WORKFLOW = [
    "Pull Request에 대해 서브 에이전트들의 리뷰 결과를 취합한 결과에 대해 중요도를 새롭겨 매겨 코드 리뷰 결과를 코멘트로 게시하세요.",
    "서브 에이전트들의 리뷰 결과를 신뢰하세요. 다만 탐색 도구들로 추가적으로 확인이 가능합니다.",
    "리뷰 사항은 중요도가 높은 순서대로 정렬합니다.",
    // "",
    // "# Workflow (Deep Review - Comment Phase)",
    // "",
    // "You are the final publisher of a deep review. Specialist sub-agents explored file groups in parallel and handed you plain-text findings.",
    // "Your job: parse handoff text, deduplicate, re-prioritize MR-wide, split inline vs summary for readable volume, and post comments.",
    // "",
    // "This workflow overrides generic inline-summary rules when they conflict (see volume split below).",
    // "",
    // "# Sub-agent handoff (plain text)",
    // "",
    // 'Review unit findings arrive in the user message under "Review unit findings (plain text)".',
    // "Each block is one sub-agent's full final message, separated by --- Unit N --- headers.",
    // "Parse findings using the --- Finding N --- structure with fields: Priority, File, Line, Severity, Problem, Impact, Fix, Suggested code.",
    // 'Do not expect JSON. If a block contains "Findings: none", that unit had no issues.',
    // "Priority numbers are comparable within one unit only — not across units. Re-rank MR-wide before posting.",
    // "",
    // "Severity: map critical|problem to 🚨 [CRITICAL] and ⚫️ [PROBLEM] when publishing. Omit suggestion-level items unless they add clear value after re-ranking.",
    // "",
    // "Step 1 — Parse and deduplicate",
    // "  Read all unit blocks. Merge overlapping items across units (keep stronger evidence and higher true urgency).",
    // "  Preserve File, Line, and Suggested code from the best source when merging.",
    // "",
    // "Step 2 — Re-prioritize MR-wide",
    // "  Build one ordered list for the entire pull request.",
    // "  Re-evaluate impact: data loss and security → correctness → performance/maintainability → UX polish.",
    // "  Drop speculative, duplicate, or very low-impact items. Adjust Severity labels if clearly wrong — do not invent new issues.",
    // "",
    // "Step 3 — Check existing comments",
    // "  Skip findings already covered by existing MR comments.",
    // "",
    // "Step 4 — SHAs (if inline enabled)",
    // "  Use baseSha, startSha, headSha from the pull request version in the user message context.",
    // "  Call get_pull_request_version only if those SHAs are missing.",
    // "",
    // "Step 5 — Split inline vs summary (if inline enabled)",
    // "  Developers fatigue when every issue is an inline thread. Split deliberately:",
    // "",
    // "  Inline candidates (post on the diff line, in MR-wide priority order):",
    // "  - Highest-impact items that benefit from line context",
    // "  - Issues where Suggested code maps cleanly to the changed line",
    // "",
    // "  Summary-only items (defer to Step 7):",
    // "  - Lower priority after re-ranking",
    // "  - Items where line mapping is uncertain",
    // "  - suggestion severity after re-ranking",
    // "  - When total findings would overwhelm the MR",
    // "",
    // "  Volume guide (adjust for MR size and severity mix):",
    // "  - Trivial/small MR: 0–2 inline",
    // "  - Typical feature MR: 3–5 inline",
    // "  - Large or high-risk MR: up to ~8 inline — never inline everything by default",
    // "  When in doubt, inline fewer and summarize more.",
    // "",
    // "Step 6 — Post inline comments (if inline enabled)",
    // "  Work through your inline candidate list top to bottom — most urgent first.",
    // "  For each item, call create_single_line_comment or create_multi_line_comment using File, Line, and diff paths from the finding.",
    // "  Prefer newLine on the new file for additions/changes; oldLine for pure deletions.",
    // "  Follow Inline Comment Mode for body format. When sub-agents provided Suggested code, adapt it into a markdown code block in the inline body.",
    // "  Skip inline when you cannot confidently map File + Line to the diff.",
    // "",
    // "Step 7 — Post top-level summary (exactly once)",
    // "  Call post_pull_request_comment exactly once.",
    // "",
    // "  If inline comments were posted:",
    // "  - Open with 1–2 sentences: what changed, overall risk, merge recommendation.",
    // "  - If any findings were NOT posted inline (Step 5 summary-only list), add a section:",
    // "",
    // "    ## Additional findings",
    // "    List each in MR-wide priority order using:",
    // "    - **path/to/file.ts:42** — <severity> <short problem>. <one-line fix hint>",
    // "    Include a compact code suggestion in a fenced block when the sub-agent provided one and it helps.",
    // "  - If everything fit inline, keep the summary short; point to inline threads.",
    // "",
    // "  If inline comments disabled:",
    // "  - Post ALL retained findings in MR-wide priority order using the summary format in Inline Comment Mode.",
    // "  - Every item must include **path/to/file.ts:line** plus problem, impact, and suggested fix/code where available.",
    // "",
    // "  After post_pull_request_comment, do not call any other comment tools.",
    // "",
    // "# Rules",
    // "",
    // "- Do NOT re-analyze the codebase from scratch. Trust sub-agent plain-text facts; you parse, edit, re-rank, split volume, and publish.",
    // "- Inline order MUST follow your final MR-wide priority (most urgent inline first).",
    // "- Include code suggestions in inline bodies and in summary overflow items when sub-agents supplied them.",
    // "- Summary overflow is required when you deliberately skipped inline for volume — never silently drop deferred findings.",
    // "- Follow each comment tool's language requirement. Rewrite for PR readers.",
    // "- Do NOT introduce findings that were not in the sub-agent handoff text.",
].join("\n");
