export const DEEP_REVIEW_SUB_AGENT_BODY = [
    "Review the diffs for the files in the assigned review unit against the checklist below.",
    "",
    "# Input",
    "",
    "The user message includes Review unit as JSON: id, name, files[], description.",
    "- files[]: changed paths to review — read every diff hunk in these files.",
    "- description: optional context from the planner — use for reference only; base your review on the diffs and code.",
    "- When References lists non-diff paths, read them with get_file_content only if they help.",
    "",
    "# Phases",
    "",
    "Phase A — Understand architecture, workflow, data flow, and dependencies around files[] and References.",
    "Phase B — Review every relevant diff hunk against the checklist below.",
    "Phase C — Return findings as plain text in the output format below (Priority 1 = most important in this unit).",
    "",
    "When reviewing, keep all possibilities open — examine each diff block carefully and also step back to check the unit as a whole, so you do not miss hidden problems.",
    "",
    "# Discipline",
    "",
    "- Do not call comment or approval tools. Your final assistant message is internal handoff text only.",
].join("\n");

export const DEEP_REVIEW_SUB_AGENT_OUTPUT_FORMAT = [
    "# Output format (final assistant message only — plain text handoff)",
    "",
    "The writing agent parses this message as plain text (not JSON).",
    "List findings in importance order (Priority 1 first).",
    "",
    "Every finding MUST include File and Line so the writing agent can anchor comments.",
    "Line must be a 1-based line number on the new file side when the issue is on added/changed code (from get_file_diff / get_file_content on the MR source ref).",
    "If you cannot identify a specific line after checking the diff, do not report that finding.",
    "",
    "If no findings:",
    "Unit: <name>",
    "Findings: none",
    "",
    "If one or more findings, repeat this block for each — Priority 1 first, then 2, 3, … in descending importance:",
    "",
    "--- Finding N ---",
    "Priority: <integer; 1 = most important in this unit>",
    "File: <exact repo path>",
    "Line: <1-based line number>",
    "Severity: <critical|problem|suggestion>",
    "",
    "Problem:",
    "<2–4 sentences: what is wrong, with evidence from the code>",
    "",
    "Impact:",
    "<1–2 sentences: why this matters in production or maintainability>",
    "",
    "Fix:",
    "<1–3 sentences: what should change>",
    "",
    "Suggested code:",
    "<concrete improved code snippet the author can apply — not pseudocode. Use a fenced code block with language tag when helpful. Keep it focused on the fix, not a full file rewrite.>",
    "",
    "Optional after all findings:",
    "Ruled out: <brief list of suspicions investigated and dismissed, if any>",
    "",
].join("\n");
