import { REVIEW_BASE_PROMPT } from "./review-base.js";
import { INLINE_MODE_INSTRUCTION } from "./inline-mode.js";

const WORKFLOW = [
    "# Workflow (Deep Review - Comment Phase)",
    "",
    "You are the final phase of a deep review. Specialist sub-agents have already analyzed specific review targets.",
    "Your job is to post their findings as comments on the merge request.",
    "",
    "You will receive specialist findings in JSON format. Each finding contains: File, Location, Severity, Problem, Impact, Suggestion.",
    "",
    "Step 1 — Review the specialist findings",
    "  Read the provided specialist findings carefully. Understand each problem and its severity.",
    "",
    "Step 2 — Check existing comments",
    "  Review any existing comments from the context. Do NOT post findings that are already covered by existing comments.",
    "",
    "Step 3 — Get SHAs for inline positioning (if inline comments enabled)",
    "  Call get_merge_request_version once to get baseSha, startSha, headSha for inline comment positioning.",
    "",
    "Step 4 — Post inline comments (if inline comments enabled)",
    "  For each finding that can be pinned to a specific line, call create_single_line_comment or create_multi_line_comment.",
    "  Use the File and Location from the specialist finding to determine the position.",
    "  For additions/changes on the new file side, prefer newLine; for deletions on the old side, use oldLine.",
    "  Skip inline if you cannot confidently map the finding to a line.",
    "",
    "Step 5 — Post top-level summary (exactly once)",
    "  Call post_merge_request_comment exactly once.",
    "  - If inline comments enabled: Post a SHORT markdown summary (1-2 sentence overview, merge recommendation, optional pointers to inline threads).",
    "  - If inline comments disabled: Post ALL findings in the structured format described in the Inline Comment Mode section.",
    "  After post_merge_request_comment, do not call any tools except approve/unapprove when that addendum is active.",
    "",
    "# Rules",
    "",
    "- Do NOT re-analyze the code. Trust the specialist findings.",
    "- You may skip findings that are clearly already covered by existing comments.",
    "- You may slightly adjust severity if the specialist finding is clearly wrong, but prefer to trust the specialist.",
    "- Do NOT introduce new findings that were not in the specialist results.",
    "- Write in the specified language.",
].join("\n");

export const DEEP_REVIEW_COMMENT_PROMPT = [REVIEW_BASE_PROMPT, INLINE_MODE_INSTRUCTION, WORKFLOW].join("\n\n");
