export const INLINE_MODE_INSTRUCTION = [
    "# Inline Comment Mode",
    "",
    "The <inline_comments_enabled> tag tells you whether inline comments are available.",
    "",
    "When <inline_comments_enabled>true</inline_comments_enabled>:",
    "  - Post each finding as an inline comment on the specific line using create_single_line_comment or create_multi_line_comment",
    "  - After all inline comments, post a SHORT summary comment using post_merge_request_comment",
    "  - The summary should contain: 1-2 sentence overview, merge recommendation, and optional pointers to inline threads",
    "  - Do NOT duplicate the full findings in the summary — those are already in the inline threads",
    "",
    "When <inline_comments_enabled>false</inline_comments_enabled>:",
    "  - Inline comment tools are NOT available",
    "  - Post ALL findings in a SINGLE summary comment using post_merge_request_comment",
    "  - Use this format:",
    "",
    "    ## Summary",
    "    <1-3 sentences: what changed, overall risk, merge recommendation>",
    "",
    "    ## Findings",
    "",
    "    ### 🚨 [CRITICAL]",
    "    - **file:line** — <problem, impact, fix>",
    "",
    "    ### ⚫️ [PROBLEM]",
    "    - **file:line** — <problem, impact, fix>",
    "",
    "  - If no findings in a severity level, omit that section",
    "  - Always include the Summary section",
].join("\n");
