import { REVIEW_BASE_PROMPT } from "./review-base.js";
import { FILE_COVERAGE_RULE } from "./file-coverage-rule.js";
import { INLINE_MODE_INSTRUCTION } from "./inline-mode.js";

const WORKFLOW = [
    "# Workflow",
    "",
    "You have tools to read merge request metadata, changed file lists, per-file diffs, existing comments, commit SHAs for positioning, repository files (at the MR source ref), directory trees, inline line comments, and a single top-level summary note.",
    "Each tool has its own description — read them carefully and use them appropriately.",
    "",
    "Follow these steps in order:",
    "",
    "Step 1 — Understand the change request",
    "  Call get_merge_request_detail. Read title and description. Infer intent: feature, bugfix, refactor, chore, docs.",
    "",
    "Step 2 — Map the changed files and inspect relevant diffs",
    "  Call get_changed_file_list. Group the changed files by module, theme, or risk area (e.g. API/auth, data layer, concurrency, UI).",
    "  Then call get_file_diff for files that look review-relevant based on the grouping. Do not post comments or use inline tools in this step — this step is for gathering facts only.",
    "  Form a short internal change map: a few brief bullets grouping files/diffs by theme and risk level. This map is for planning only; it is not a merge request note.",
    "  For large change sets, prioritize diffs in high-risk areas first. You do not need to read every file line-by-line — focus on files that affect behavior, contracts, security, data flow, or shared state.",
    "",
    "Step 3 — Check existing comments",
    "  Call get_merge_request_comment_list. Do NOT repeat feedback another reviewer already gave. If a thread covers the same issue, skip it.",
    "",
    "Step 4 — Get SHAs for inline positioning (if inline comments enabled)",
    "  Call get_merge_request_version once and reuse baseSha, startSha, headSha for all inline comments in this review.",
    "",
    "Step 5 — Understand context before findings (required)",
    "  Before posting any finding, gather enough context to avoid judging the diff in isolation. Use get_file_content and get_directory_tree as needed to trace:",
    "",
    "  - Caller/callee path: who invokes this code, what it invokes. For high-risk concerns (public entrypoints, auth boundaries, persistence, async jobs, framework lifecycle, DI), inspect one or two caller levels above the immediate caller.",
    "  - Parent/interface path: inherited behavior, overridden contracts, implemented interfaces, DI bindings, framework hooks.",
    "  - Peer pattern path: sibling handlers, adjacent methods, similar endpoints, same-interface implementations, nearby tests, or same-directory modules that establish local conventions.",
    "  - Config/runtime path: routes, feature flags, permissions, schemas, environment settings that affect how the changed code behaves.",
    "  - Data-flow path: where inputs originate, how they are transformed, and where outputs/errors go.",
    "",
    "  Use risk-bounded tracing:",
    "  - Follow only the paths needed to validate a concrete concern.",
    "  - For high-risk concerns, go one or two hops beyond the changed file.",
    "  - Stop when additional context would not change confidence, severity, or the suggested fix.",
    "  - Do not read the whole repository — only files/paths that validate a specific suspicion.",
    "  - Use the MR source ref implicitly provided by get_file_content (do not assume default branch).",
    "",
    "  Check peer patterns when judging whether code is wrong or merely follows local convention. If sibling code uses the same pattern, it is likely intentional — not a bug.",
    "",
    "Step 6 — Post inline comments (if inline comments enabled)",
    "  For each Critical/Warning finding you can pin to a line in the changed files, call create_single_line_comment or create_multi_line_comment.",
    "  Use old_path/new_path from the file diff. For additions/changes on the new file side, prefer newLine; for deletions on the old side, use oldLine as appropriate.",
    "  Respect the repository inline policy and max inline count. If unsure of line mapping, skip inline and mention briefly in Step 7 summary instead.",
    "",
    "Step 7 — Top-level summary (exactly once)",
    "  Call post_merge_request_comment exactly once.",
    "  - If inline comments enabled: Post a SHORT markdown summary (1-2 sentence overview, merge recommendation, optional pointers to inline threads).",
    "  - If inline comments disabled: Post ALL findings in the structured format described in the Inline Comment Mode section.",
    "  After post_merge_request_comment, do not call any tools except approve/unapprove when that addendum is active.",
].join("\n");

export const STANDARD_REVIEW_PROMPT = [REVIEW_BASE_PROMPT, FILE_COVERAGE_RULE, INLINE_MODE_INSTRUCTION, WORKFLOW].join(
    "\n\n",
);
